# Environment variables set for all `cargo ...` commands.
[env]

# This file will not deploy to Kubernetes - should be managed by secrets

# Scope down tracing, to filter out external lib tracing
RUST_LOG="rust_start=debug" # comment out for error only tracing, change info to debug for verbose
SERVICE_CONFIG_VAR_ONE="config var one"
SERVICE_CONFIG_VAR_TWO="config var two"

DB_HOST="host.docker.internal"
DB_PORT="9088"
DB_NAME="sysmaster"
DB_USER="informix"
DB_PASSWORD="in4mix"
INFORMIXSERVER="informix"

